### PR TITLE
Fix unit Type and User

### PR DESCRIPTION
**Pull request by autra**
I'm doing the same change that were made for lufi:

https://github.com/YunoHost-Apps/lufi_ynh/pull/36 
https://github.com/YunoHost-Apps/lufi_ynh/pull/38

## Package_check results
---
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/lstu_ynh%20PR43%20(yalh76)/)

### CODE REVIEW

**Comment by autra** [comment]
Waiting for ci-dev before switching to "ready for review"

**Comment by autra** [comment]
mmhh not sure I'm right with `User=__APP__`

**Review by alexAubin — APPROVED** [review]
LGTM?

**Comment by alexAubin** [comment]
Merging because this is consistent with lufi also based on carton

**Pull request merged**
